name: Publish to NuGet

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

jobs:
    build:
        name: Build and Publish
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Pack
              run: dotnet pack --configuration Release --no-build --output ./nupkg

            - name: Upload NuGet package
              uses: actions/upload-artifact@v4
              with:
                  name: nuget-package
                  path: ./nupkg/*.nupkg
                  if-no-files-found: error
                  retention-days: 7

            - name: Publish to NuGet
              run: dotnet nuget push "./nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
